### obtener la url de la aplicación
POST http://localhost:3000/register 
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.col",
  "password": "Securepassword123",
  "phone": "+1234567890",
  "role": "user",
  "address": {
    "calle": "123 Main St",
    "numero": "456",
    "ciudad": "Anytown",
    "comuna": "Anycomuna",
    "region": "Anyregion",
    "pais": "Anycountry",
    "sql": "SELECT * FROM users"
  }
}

### obtener user por email
GET http://localhost:3000/users/john.doe@example.com

### eliminar un usuario
DELETE http://localhost:3000/users/john.doe@exampl


### editar usuario
PATCH  http://localhost:3000/users/edit/john.doe@example.com
Content-Type: application/json

{
  "address": {
    "numero": "333"
  }
}

### editar direccion
PATCH  http://localhost:3000/users/datos-direccion/john.doe@example.com
Content-Type: application/json

{
    "calle": "123 Main St",
    "numero": "456",
    "ciudad": "Anytown",
    "comuna": "Anycomuna",
    "region": "Anyregione"
}


### Crear Propiedad
POST http://localhost:3000/properties
Content-Type: application/json

{
  "address": "123 Main St",
  "ciudad": "Santiago",
  "comuna": "Las Condes",
  "price": 250000,
  "description": "Hermosa casa en una excelente ubicación.",
  "bathrooms": 2,
  "rooms": 3,
  "area": 120,
  "photo_url": "http://example.com/photo.jpg",
  "sale_type": "Venta",
  "property_type": "Casa"
}

### obtener propiedades por id
GET http://localhost:3000/properties/17125eb6-3182-4c81-9c4b-2717dc0767c4

### Eliminar Propiedad por id
DELETE http://localhost:3000/properties/17125eb6-3182-4c81-9c4b-2717dc0767c4

### Editar Propiedad por id
PATCH http://localhost:3000/properties/17125eb6-3182-4c81-9c4b-2717dc0767c4
Content-Type: application/json

{
  "price": 300000
}

###login 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "john.doe@example.col",
  "password": "Securepassword12"
}